apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-backend
  labels:
    app: financeguard-backend
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: financeguard-backend
  template:
    metadata:
      labels:
        app: financeguard-backend
    spec:
      containers:
        - name: backend
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 8000
          env:
            - name: ENVIRONMENT
              value: {{ .Values.env.ENVIRONMENT | quote }}
            - name: SKIP_AUTH_VERIFICATION
              value: {{ .Values.env.SKIP_AUTH_VERIFICATION | quote }}
          resources:
            limits:
              cpu: {{ .Values.resources.limits.cpu }}
              memory: {{ .Values.resources.limits.memory }}
            requests:
              cpu: {{ .Values.resources.requests.cpu }}
              memory: {{ .Values.resources.requests.memory }}