apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: financeguard-backend-prod
  namespace: argocd
  annotations:
    argocd.argoproj.io/managed-by-pipeline: "true"
spec:
  project: default
  source:
    repoURL: https://github.com/timkamba2002/financeguard-devsecops-capstone.git
    targetRevision: main
    path: helm/backend
    helm:
      valueFiles:
        - values.yaml
        - values-prod.yaml
      parameters:
        - name: image.tag
          value: "77901f7b36aabecdae7236e6d5a9571952ccb50a"
  destination:
    server: https://kubernetes.default.svc
    namespace: prod
  syncPolicy:
    automated:
      prune: false # prod: never auto-prune — manual confirmation required
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
