apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: financeguard-backend-prod
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/timkamba2002/financeguard-devsecops-capstone.git
    targetRevision: main
    path: helm/backend
    helm:
      valueFiles:
        - values.yaml
        - values-prod.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: prod
  syncPolicy:
    automated:
      prune: false      # prod: never auto-prune, require manual confirmation
      selfHeal: true
