apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: financeguard-frontend-prod
  namespace: argocd
  annotations:
    argocd.argoproj.io/managed-by-pipeline: "true"
spec:
  project: default
  source:
    repoURL: https://github.com/timkamba2002/financeguard-devsecops-capstone.git
    targetRevision: main
    path: helm/frontend
    helm:
      valueFiles:
        - values.yaml
        - values-prod.yaml
      parameters:
        - name: image.tag
          value: "0c1f12efb00f67dfae59d3501edd4ad20a1590a1"
  destination:
    server: https://kubernetes.default.svc
    namespace: prod
  syncPolicy:
    automated:
      prune: false # prod: never auto-prune
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
