apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: otel-collector
  namespace: argocd
spec:
  project: default
  sources:
    - repoURL: https://open-telemetry.github.io/opentelemetry-helm-charts
      chart:   opentelemetry-collector
      targetRevision: "0.96.0"
      helm:
        valueFiles:
          - $values/k8s/observability/otel-collector/values.yaml
    - repoURL: https://github.com/timkamba2002/financeguard-devsecops-capstone.git
      targetRevision: main
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    automated:
      prune:    true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
