apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: tempo
  namespace: argocd
spec:
  project: default
  sources:
    - repoURL: https://grafana.github.io/helm-charts
      chart:   tempo
      targetRevision: "1.7.2"
      helm:
        valueFiles:
          - $values/k8s/observability/tempo/values.yaml
    - repoURL: https://github.com/timkamba2002/financeguard-devsecops-capstone.git
      targetRevision: main
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    automated:
      prune:    true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
