apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: financeguard-backend-staging
  namespace: argocd
  annotations:
    argocd.argoproj.io/managed-by-pipeline: "true"
spec:
  project: default
  source:
    repoURL: https://github.com/timkamba2002/financeguard-devsecops-capstone.git
    targetRevision: main
    path: helm/backend
    helm:
      releaseName: financeguard-backend
      valueFiles:
        - values.yaml
        - values-staging.yaml
      parameters:
        - name: image.tag
          value: "0fb51a8687c9c6f5f67eeeaacab668dde7b146c5"
  destination:
    server: https://kubernetes.default.svc
    namespace: staging
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
