apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: financeguard-frontend-staging
  namespace: argocd
  annotations:
    argocd.argoproj.io/managed-by-pipeline: "true"
spec:
  project: default
  source:
    repoURL: https://github.com/timkamba2002/financeguard-devsecops-capstone.git
    targetRevision: main
    path: helm/frontend
    helm:
      valueFiles:
        - values.yaml
        - values-staging.yaml
      parameters:
        - name: image.tag
          value: "2e2d547e7b84da0f6228730be4dd7ac7ecd50e7f"
  destination:
    server: https://kubernetes.default.svc
    namespace: staging
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
