apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: financeguard-frontend-dev
  namespace: argocd
  annotations:
    argocd.argoproj.io/managed-by-pipeline: "true"
spec:
  project: default
  source:
    repoURL: https://github.com/timkamba2002/financeguard-devsecops-capstone.git
    targetRevision: main
    path: helm/frontend
    helm:
      releaseName: financeguard-frontend
      valueFiles:
        - values.yaml
        - values-dev.yaml
      parameters:
        - name: image.tag
          value: "c72a0e1ac7e37d9f18fd8f306aa087773a623762"
  destination:
    server: https://kubernetes.default.svc
    namespace: dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
