apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: dev

configMapGenerator:
  - name: backend-config
    literals:
      - ENVIRONMENT=dev
      - SKIP_AUTH_VERIFICATION=true

patches:
  - target:
      kind: Deployment
      name: .*backend
    patch: |-
      - op: replace
        path: /spec/replicas
        value: 2
  - target:
      kind: Deployment
      name: .*frontend
    patch: |-
      - op: replace
        path: /spec/replicas
        value: 2
