replicaCount: 2

image:
  tag: "latest"

env:
  ENVIRONMENT: "staging"
  SKIP_AUTH_VERIFICATION: "false"

autoscaling:
  enabled: true
  minReplicas: 2
  maxReplicas: 5
  targetCPUUtilizationPercentage: 75

ingress:
  enabled: true

otelSidecar:
  enabled: true
